keys:
  - &users
    - &willg age10c02spktse006k0jgucc7refhe6jl4s8n9ukjqazv7mw6mdc6yas93cjjg
  - &hosts
    - &andromeda age19ff59k2eqtvf2sx62uuxrag2npc70ua52qwv0h2r80wvprtdj99sggesmf
creation_rules:
  - path_regex: secrets\/secrets\.yaml$
    key_groups:
      - age:
          - *willg
          - *andromeda
  - path_regex: secrets\/andromeda\.yaml$
    key_groups:
      - age:
          - *willg
          - *andromeda
  - path_regex: secrets\/willg\.yaml$
    key_groups:
      - age:
          - *willg
