#!/bin/sh

# Check if exactly one argument is provided
if [ "$#" -ne 1 ]; then
  echo "Error: This script requires the flake name."
  exit 1
fi

# Update the flake
sudo nix flake update

# Rebuild NixOS with the provided argument
sudo nixos-rebuild switch --flake .#$1
